# Generated by Django 4.1.5 on 2023-01-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_description',
            field=models.CharField(default='1', max_length=361),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_nature',
            field=models.CharField(default='1', max_length=28),
        ),
    ]
