# Generated by Django 4.1.5 on 2023-01-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_transaction_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_description',
            new_name='l',
        ),
    ]
