# Generated by Django 4.1.5 on 2023-01-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_rename_transaction_description_transaction_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='test',
            field=models.CharField(default='teste', max_length=61),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='l',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
