# Generated by Django 4.1.5 on 2023-01-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transaction_test_alter_transaction_l'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='l',
            new_name='transaction_description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='test',
        ),
    ]
